### PR TITLE
WPF Subgraph Label

### PR DESCRIPTION
**Pull request by Brains**
Implementation for #128, #276

Just enabled `TextBlock` creation for `Subgraph`. ~~Only at `Top` position for now (better than nothing).~~
Then fixed some overlapping issues

### CODE REVIEW

**Comment by Brains** [comment]
Currently, `WpfApplicationSample` looks so right after the launch
image

No margins around subgraph labels, but dragging elements or collapse/expand fixes that instantly
image

**Comment by Brains** [comment]
The last commit fixes no margins issues
The only problem is the edge from `58` to `Inner` subgraph. But noticed it is really buggy even in other cases, like dragging `Inner` subgraph.

image

**Comment by Brains** [comment]
Collapsed `Outer Subgraph`
image

But collapsing `Inner` crashes on
image
at
```
AutomaticGraphLayout.dll!Microsoft.Msagl.Routing.ShapeCreator.GetShapesOnDict(System.Collections.Generic.Dictionary<Microsoft.Msagl.Core.Layout.Node, Microsoft.Msagl.Routing.Shape> nodesToShapes, Microsoft.Msagl.Core.Layout.Cluster c) Line 51	C#
AutomaticGraphLayout.dll!Microsoft.Msagl.Routing.ShapeCreator.GetShapes(Microsoft.Msagl.Core.Layout.GeometryGraph graph) Line 31	C#
AutomaticGraphLayout.dll!Microsoft.Msagl.Routing.SplineRouter.SplineRouter(Microsoft.Msagl.Core.Layout.GeometryGraph graph, System.Collections.Generic.IEnumerable<Microsoft.Msagl.Core.Layout.Edge> edges, double tightPadding, double loosePadding, double coneAngle, Microsoft.Msagl.Core.Routing.BundlingSettings bundlingSettings) Line 128	C#
AutomaticGraphLayout.dll!Microsoft.Msagl.Miscellaneous.LayoutHelpers.RouteAndLabelEdges(Microsoft.Msagl.Core.Layout.GeometryGraph geometryGraph, Microsoft.Msagl.Core.Layout.LayoutAlgorithmSettings layoutSettings, System.Collections.Generic.IEnumerable<Microsoft.Msagl.Core.Layout.Edge> edgesToRoute, int straighLineRoutingThreshold, Microsoft.Msagl.Core.CancelToken cancelToken) Line 205	C#
AutomaticGraphLayout.dll!Microsoft.Msagl.Layout.Initial.Relayout.RunInternal() Line 89	C#
AutomaticGraphLayout.dll!Microsoft.Msagl.Core.AlgorithmBase.Run() Line 17	C#
AutomaticGraphLayout.Drawing.dll!Microsoft.Msagl.Drawing.LayoutEditor.CollapseCluster(Microsoft.Msagl.Core.Layout.Cluster cluster) Line 372	C#
AutomaticGraphLayout.Drawing.dll!Microsoft.Msagl.Drawing.LayoutEditor.RelayoutOnIsCollapsedChanged(Microsoft.Msagl.Drawing.IViewerNode iCluster) Line 306	C#
Microsoft.Msagl.WpfGraphControl.dll!Microsoft.Msagl.WpfGraphControl.VNode.InvokeIsCollapsedChanged() Line 172	C#
Microsoft.Msagl.WpfGraphControl.dll!Microsoft.Msagl.WpfGraphControl.VNode.TopMarginRectMouseLeftButtonDown(object sender, System.Windows.Input.MouseButtonEventArgs e) Line 184	C#
```

However, same crash happens on `master`, guess not related to this PR.

**Comment by Brains** [comment]
Now label position depends on `LgNodeInfo.LabelPlacement`. Same problem with the edge from `58`.

image

**Comment by levnach** [comment]
@Brains, thank to working on it. 
The crash in GetShapesOnDict can be fixed as follows:
`foreach (var cc in c.Clusters) {
                if (cc.IsCollapsed) continue;
                GetShapesOnDict(nodesToShapes, cc);
                cShape.AddChild(nodesToShapes[cc]);
            }`
But then the problems, further crashes, persist in master. I will try to work on it later.  I think the pull request needs to be merged after the crashes are fixed and the edge routing works correctly.

**Comment by Brains** [comment]
> image

Fixed
image

**Comment by Brains** [comment]
> I think the pull request needs to be merged after the crashes are fixed and the edge routing works correctly.

Fixed edge routing
Fixed overlap of `CollapseButton` in collapsed state and few minor things
Seems like all issues related to this PR were resolved

But the crash really has no connection to my PR, it was there before on `master`. I tried to figure out why it happened but stuck completely, too complex, really no idea. Consider the PR and the crash separately please, they are not related to each other.

**Comment by levnach** [comment]
Thanks for the change! I will try to fix the routing bugs.

**Comment by Brains** [comment]
Thank you for doing this cool project

**Pull request merged**
