### PR TITLE
Switch to net Standard

### PR DESCRIPTION
**Pull request by paulovila**

### CODE REVIEW

**Comment by FilippoPolo** [comment]
Looks good at a quick glance; I'll review this more thoroughly asap. Also adding Lev.

**Comment by paulovila** [comment]
Sure, I also made sure the nuget packages buid

**Comment by FilippoPolo** [comment]
The debug configuration of GraphLayout.sln is not building for me.

**Comment by levnach** [comment]
Sorry, I do not access to a windows machine until 5th of March. Cannot review.

**Comment by paulovila** [comment]
I'll have a look tonight. I  just did the release one.

**Comment by FilippoPolo** [comment]
Seems to be working now.

**Pull request merged**
