### PR TITLE
Changes to handle DragEnd event, show LayoutEditor form and allow edge re-routing only from user code.

### PR DESCRIPTION
**Pull request by lafrank**
Added DragEnded event handler to GraphViewerGDI.
Added public method GraphViewerGDI.ShowLayoutSettingsEditor().
Added public method GraphViewerGDI.RerouteGraph() to allow edge rerouting without layout recalculation.

### CODE REVIEW

**Comment by levnach** [comment]
I think this directory has been added by mistake GraphLayout/packages/Newtonsoft.Json.10.0.3.

**Comment by lafrank** [comment]
Yes, most probably ir was. I'll update it.

**Comment by lafrank** [comment]
Reopening this after the offending package was removed.

**Comment by levnach** [comment]
Sorry Laszlo, I cannot accept this request. It seems there are a lot of changes just because of the formatting. The differences are very large, so examining them by eye does not work anymore. It would require some extensive testing to be sure that some bugs would not get in.

**Comment by lafrank** [comment]
I quite understand that. Will try to revert formatting.

**Pull request closed without merging**
