### PR TITLE
Update NuGet package to contain Drawing and GraphViewerGDI

### PR DESCRIPTION
**Pull request by juhan**
The tiny patch includes Microsoft.Msagl.Drawing.dll, Microsoft.Msagl.GraphViewerGDI.dll and appropriate hint files in the NuGet package. Also suggested a cleanup, as NuGet executable can be assumed to be present on a development system.

### CODE REVIEW

**Comment by msftgits** [comment]
Hi, I am closing and re-opening this PR to bump the CLA bot. Sorry for the inconvenience!

**Comment by levnach** [comment]
Thank you!

**Comment by wirmar** [comment]
This change to the nuget package does not seem to have been published. Can someone please publish it or tell me how I can help?

**Comment by juhan** [comment]
It was previously uploaded to NuGet by @saveenr. @saveenr, could you please regenerate and upload the NuGet package? The only major change is that it now requires NuGet.exe to be available in the system.

**Comment by saveenr** [comment]
This commit is a great starting point! I had  look at the relevant commits and this related https://github.com/Microsoft/automatic-graph-layout/issues/4 and suggest we proceed with multiple packages as some consumers only need the layout and not the rendering.


Synthesizing from the comments from rassilon, levnach, and a few others, I'm thinking something like


Microsoft.Automatic.Graph - which contains only Msagl.dll

Microsoft.Automatic.Graph.WinForms -  Msagl.Drawing.dll and Masagl.GraphViewerGDI and takes  dependency on Microsoft.Automatic.Graph

Microsoft.Automatic.Graph.WPF - etc.

Microsoft.Automatic.Graph.Silverlight - etc.

I'll contact Lev and have an chat with him about how to proceed. Hope to get something published very soon.

________________________________

**Comment by jobubo** [comment]
> I'll contact Lev and have an chat with him about how to proceed. Hope to get something published very soon.

Thank you very much for contacting Lev, I am looking forward for the nuget packages as well. Any new on this topic?

**Comment by sbrl** [comment]
What's the status of including the drawing namespace in the Nuget package? Is there a workaround I could use in the meantime?

**Comment by saveenr** [comment]
An updated set of packages will be updated very soon - apologies for the delay

**Comment by sbrl** [comment]
@saveenr Awesome, thanks 😺

**Comment by saveenr** [comment]
We've published newer packages. Can you please try it out and tell us what you think?

- Microsoft.Automatic.Graph.Layout 
- Microsoft.Automatic.Graph.WinForms (contains the Drawing namespace)

In the future the Drawing namespace might be its own NuGet package. So feedback on that idea would be appreciated!

**Comment by blumu** [comment]
Thanks. Unfortunately I cannot test if this works for me until you release `Microsoft.Msagl.GraphViewerGDI.dll` as well as a Nuget package: the version of `Microsoft.Msagl.GraphViewerGDI.dll` I'm using is an older version that is not compatible with the Nuget versions of `Microsoft.Automatic.Graph.Drawing` and `Microsoft.Automatic.Graph.Layout` :-(

**Comment by saveenr** [comment]
Good news! :-) Please check NuGet again - we just released all three packages with standardized names about 30 minutes ago!

- Microsoft.Msagl 
- Microsoft.Msagl.Drawing
- Microsoft.Msagl.GraphViewerGDI

**Comment by blumu** [comment]
Awesome! Perfect timing :-) I will give it a try!

**Comment by blumu** [comment]
I have successfully migrated from version 1.0 of GLEE (from 2006!) to the new `Microsoft.Msagl` Nuget packages! Fortunately the API did not change too much over the past 11 years so I only had to make minor changes to my code. Everything seems to work as before!

**Comment by saveenr** [comment]
Fantastic! Thanks for checking back in on this thread!

**Comment by fwaris** [comment]
are we getting the WPF control as nuget package?
One reason to use WPF is for collapsible subgraphs. Not sure if that functionality is present in the GDI viewer.

**Pull request merged**
