### PR TITLE
Fix Hexagon

### PR DESCRIPTION
**Pull request by paulovila**
Display Hexagon, and prevent the lines to overlap the content

### CODE REVIEW

**Comment by levnach** [comment]
Thanks

**Comment by paulovila** [comment]
The overlap is not back:

image

**Comment by levnach** [comment]
To avoid the overlap figure out the width and the height of the hexagon

**Comment by paulovila** [comment]
The height of the hexagon is height of the box, the width of the hexagon can be height/2 + width height/2 .
The problem now is that the sides of the hexagon are crossing over box.
Shouldn't it be like this?
image

**Comment by levnach** [comment]
Paulo, please check out the new version, which is almost yours with a few touches.

**Comment by paulovila** [comment]
Yes it seems to display the same, regardless is  "+ center" or "- center", but I suppose it is better +center

**Pull request merged**
