### PR TITLE
Add compatibility with Net461

### PR DESCRIPTION
**Pull request by paulovila**

### CODE REVIEW

**Comment by paulovila** [comment]
https://github.com/microsoft/automatic-graph-layout/pull/269

**Comment by paulovila** [comment]
The nuget packages https://www.nuget.org/packages/AutomaticGraphLayout/
https://www.nuget.org/packages/AutomaticGraphLayout.Drawing/ are already **netStandard**
Based on this: https://dotnet.microsoft.com/platform/dotnet-standard
the minimum compatible version for referenfing netstandard 2.0 is .Net 4.6.1, so my advise is to add (not downgrade) 4.6.1 in AutomaticGraphLayout.WpfGraphControl target along with its nuget package

**Comment by levnach** [comment]
@paulovila , thank you for working on this! There are conflicts in merge that need to be resolved.

**Comment by paulovila** [comment]
sure, I'll see it tomorrow, I noticed the build script also needs some update

**Comment by levnach** [comment]
@baruchiro, can you please check that this chance works for you? Paulo published a new nuget built from this change, so you might to build with the nuget.

**Pull request merged**
