### PR TITLE
Drag of Rectilinear Edges not affects Subgraph

### PR DESCRIPTION
**Pull request by Brains**

### CODE REVIEW

**Comment by Brains** [comment]
After the fix it looks ok.
But I am worrying the fix is too simple, too easy to be right.

**Comment by Brains** [comment]
> But I am worrying the fix is too simple and too easy to be correct

I was right. Back to draft, trying to fix

**Comment by Brains** [comment]
Fixed dragging of `Subgraph` content

However, I am really worry about my fix. Just dumbly copied few lines from nearby `DragWithStraightLines` method without real understanding of code. Seems works though.

**Comment by levnach** [comment]
I think I fixed some crashes when routing with clusters.

**Comment by Brains** [comment]
> I think I fixed some crashes when routing with clusters.

That's good. Thanks

**Comment by Brains** [comment]
And noticed just now that I forgot to revert changes in `WpfApplicationSample`. You reverted them. Sorry about that.

**Pull request merged**
