### PR TITLE
Clean-up of code base

### PR DESCRIPTION
**Pull request by stefanloerwald**
- removed dead code
- fixed some comments
- removed useless Console.Write*
- replaced debug Console.Write* by System.Diagnostics.Debug.Write*

Addresses #244

### CODE REVIEW

**Comment by levnach** [comment]
Thank you, Stefan!

**Comment by stefanloerwald** [comment]
Thanks for merging :-)

Will there be an updated nuget package soon?

**Comment by levnach** [comment]
That's not me who produces the nuget usually.

Sent from a phone
________________________________

**Comment by stefanloerwald** [comment]
That's fine for me ;-) Who can I get in touch with then?

**Comment by SMTStuck** [comment]
According to the MSAGL [NuGet](url) page it is owned by pvila, not much of a stretch to consider this to be [paulovila](https://github.com/paulovila) as he is also a contributor to the project.

**Comment by levnach** [comment]
@paulovila , can you be so kind as to create a NuGet for Msagl with the latest updates?

**Comment by paulovila** [comment]
Hi Lev, sure  I’m travelling in a few hours, I’ll
Do it later tonight
Regards,
PV
________________________________

**Pull request merged**
