### PR TITLE
Downgrade to support net471

### LINKED ISSUE #267: Support net471
https://github.com/microsoft/automatic-graph-layout/blob/58c76c9d56196002ddb9f22ce4807b7f971bf042/GraphLayout/tools/WpfGraphControl/WpfGraphControl.csproj#L4

Hi, why is this targeted as `net472`?

As far as I can understand, you want to target the lowest platform in order to support more projects, right?

I have a very large project in `net471`, I can't upgrade it easily to `net472`.

And another question, why not use `netstandard`?

### PR DESCRIPTION
**Pull request by baruchiro**
close #267

### CODE REVIEW

**Comment by levnach** [comment]
@baruchiro , will change https://github.com/microsoft/automatic-graph-layout/pull/269 work for you?

**Comment by baruchiro** [comment]
Yes I think so, Thanks

**Comment by paulovila** [comment]
Hi @baruchiro Can you please check v1.1.10
https://www.nuget.org/packages/AutomaticGraphLayout.WpfGraphControl
https://www.nuget.org/packages/AutomaticGraphLayout.GraphViewerGDI

they both depend in the netstandard packages:
https://www.nuget.org/packages/AutomaticGraphLayout
https://www.nuget.org/packages/AutomaticGraphLayout.Drawing

**Comment by baruchiro** [comment]
I finally choose the GraphX library, so I not working on this project anymore.

But it seems to be OK now, I managed to install the new nuget in my project.

**Comment by levnach** [comment]
Thanks for checking!

**Pull request closed without merging**
