### PR TITLE
Netcore upgrade

### PR DESCRIPTION
**Pull request by MikaelFerland**
Hi, the GraphViewerGDI is now working netcoreapp3.1 so #239.
I upgraded also each sample .csproj with the new format, added .netcoreapp3.1 as target and replaced the no more existing controls. You should be able to publish the package on NuGet after the PR.

### CODE REVIEW

**Comment by levnach** [comment]
Thanks Mikael! Who is going to produce the nuget? I have not done it so help would be appreciated.

**Comment by MikaelFerland** [comment]
Hi @levnach thank you for the merge!
What is your actual publishing strategy (versioning, publishing)?
Shouldn't it be at the same package owner to publish it?

**Comment by levnach** [comment]
@MikaelFerland , can you please to look at the issue that seems resulted after your pull request?
Untitled

**Comment by MikaelFerland** [comment]
Hi @levnach I'm sorry to see that. The error will no more happen in VS 2019 from 16.7.X and above. It's seem that VS is sensitive to the new project format. The only workaround I found is to use VS 2019 16.7.X preview until we get the fix in the none preview version. Otherwise we have to downgrade VS 2019 to somewhere around 16.4.X  :( . I'm using the preview version.

I'm really sorry about it, but it's not under my control.

You can see it here https://developercommunity.visualstudio.com/content/problem/992414/project-system-data-flow-dataflowblockslim-actionblockslimasync1-42526823-closed-because-of-an-exception-systemaggregateexception-one-or-more-errors-occurred-----systeminvalidoperationexception-unexpected-false.html

**Comment by odedshimon** [comment]
Joins the request for a Nugget version with Core 3.1 support.

**Comment by levnach** [comment]
I think @paulovila  has produced it at https://www.nuget.org/packages/AutomaticGraphLayout/1.1.9

**Comment by odedshimon** [comment]
Thank you for your response @levnach.
I have installed @paulovila version from the link above,
But still got the same exception:
**Could not load type 'System.Windows.Forms.ToolBar'** 
image

**Comment by paulovila** [comment]
Sorry the Forms/WPF-net472/netCore3 packages where published (v1.1.9): 
Forms: https://www.nuget.org/packages/AutomaticGraphLayout.GraphViewerGDI
WPF:    https://www.nuget.org/packages/AutomaticGraphLayout.WpfGraphControl
Let me know if it works for you

**Comment by odedshimon** [comment]
It worked just fine.
I have managed to migrate my whole project to .Net Core.
Thank you guys very much!

**Pull request merged**
